import React, { useState, useMemo, useEffect } from "react";
import { useQuery } from "@tanstack/react-query";
import { base44 } from "api/base44Client";
import { useLocation, Link } from "react-router-dom";
import { createPageUrl } from "utils";
import { Card } from "components/ui/card";
import { Button } from "components/ui/button";
import { motion, AnimatePresence } from "framer-motion";
import MotionContainer, { fadeUp } from "components/ui/motion";
import { Building2, MapPin, Calendar } from "lucide-react";
import { Skeleton } from "components/ui/skeleton";
import { Input } from "components/ui/input";
import ProjectModal from "components/ui/project-modal";
import localProjectsManifest from "../entites/projets_auto.json";
import PictureCard from 'components/ui/picture-card';

export default function Projets() {
  const [filter, setFilter] = useState("tous");
  const [q, setQ] = useState("");
  const [selectedProject, setSelectedProject] = useState(null);
  const [modalOpen, setModalOpen] = useState(false);
  const INITIAL_VISIBLE = 6;
  const [visibleCount, setVisibleCount] = useState(INITIAL_VISIBLE);

  const { data: apiProjets = [], isLoading } = useQuery({
    queryKey: ['projets'],
    queryFn: () => base44.entities.Projet.list('-created_date'),
  });

  function buildSrc(url, w) {
    if (!url) return url;
    try {
      const [base, q] = url.split('?');
      const params = new URLSearchParams(q || '');
      if (base.startsWith('/')) return base;
      params.set('w', String(w));
      params.set('q', params.get('q') || '80');
      return `${base}?${params.toString()}`;
    } catch (e) {
      return url;
    }
  }

  // no per-card expansion; keep modal + links like `programme_pach`

  // Map local manifest shape (generated by scripts/ingest_projets.js) to UI shape
  const manifestProjects = useMemo(() => {
    try {
      const list = (localProjectsManifest && Array.isArray(localProjectsManifest.projects)) ? localProjectsManifest.projects : [];
      return list.map(p => ({
        id: p.id || p.slug || `${p.type}_${p.title}`,
        titre: p.title || p.titre || p.slug,
        image_principale: p.cover || (p.images && p.images[0] && (typeof p.images[0] === 'string' ? p.images[0] : p.images[0].url)) || null,
        images: (p.images || []).map(i => (typeof i === 'string' ? i : i.url)).filter(Boolean),
        categorie: p.type || p.categorie || 'autre',
        description: p.shortDesc || p.description || '',
        localisation: p.localisation || '',
        superficie: p.superficie || '',
        duree: p.duree || '',
        statut: p.statut || 'termine'
      }));
    } catch (e) {
      return [];
    }
  }, [localProjectsManifest]);

  // prefer manifest if it contains projects, otherwise use API data
  const projets = manifestProjects.length > 0 ? manifestProjects : (apiProjets || []);

  const categories = [
    { value: "tous", label: "Tous les Projets" },
    { value: "residentiel", label: "Résidentiel" },
    { value: "commercial", label: "Commercial" },
    { value: "infrastructure", label: "Infrastructure" },
    { value: "renovation", label: "Rénovation" }
  ];

  // derive categories dynamically from fetched projets
  const dynamicCategories = useMemo(() => {
    const cats = Array.from(new Set(projets.map(p => p.categorie).filter(Boolean)));
    const mapped = cats.map(c => ({ value: c, label: c.charAt(0).toUpperCase() + c.slice(1) }));
    return [{ value: 'tous', label: 'Tous les Projets' }, ...mapped];
  }, [projets]);

  const filteredProjets = useMemo(() => {
    let list = filter === "tous" ? projets : projets.filter(p => p.categorie === filter);
    if (q && q.trim().length > 0) {
      const term = q.trim().toLowerCase();
      list = list.filter(p => (p.titre || "").toLowerCase().includes(term) || (p.description || "").toLowerCase().includes(term) || (p.localisation || "").toLowerCase().includes(term));
    }
    return list;
  }, [projets, filter, q]);

  // reset visibleCount when filter or query changes
  useEffect(() => {
    setVisibleCount(INITIAL_VISIBLE);
  }, [filter, q]);

  const location = useLocation();
  useEffect(() => {
    if (location.hash) {
      const id = location.hash.replace('#', '');
      setTimeout(() => {
        const el = document.getElementById(id);
        if (el) el.scrollIntoView({ behavior: 'smooth', block: 'start' });
      }, 50);
    }
  }, [location]);

  // prepare gallery content to avoid large nested JSX inside return
  const galleryContent = isLoading ? (
    <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
      {[1, 2, 3, 4, 5, 6].map((i) => (
        <Card key={i} className="overflow-hidden animate-pulse">
          <div className="h-64 bg-gray-200" />
          <div className="p-6 space-y-3">
            <div className="h-4 bg-gray-200 rounded w-3/4" />
            <div className="h-3 bg-gray-200 rounded w-full" />
            <div className="h-3 bg-gray-200 rounded w-5/6" />
          </div>
        </Card>
      ))}
    </div>
  ) : filteredProjets.length === 0 ? (
    <div className="text-center py-20">
      <Building2 className="w-16 h-16 text-gray-400 mx-auto mb-4" />
      <h3 className="text-xl font-semibold text-gray-600 mb-2">Aucun projet dans cette catégorie</h3>
      <p className="text-gray-500">Revenez bientôt pour découvrir nos nouveaux projets</p>
    </div>
  ) : (
    <>
      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
        <AnimatePresence mode="popLayout">
          {filteredProjets.slice(0, visibleCount).map((projet, index) => {
            return (
              <motion.div
                key={projet.id}
                layout
                initial={{ opacity: 0, y: 14 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: 8 }}
                transition={{ duration: 0.28, delay: index * 0.03 }}
              >
                      <motion.div layout whileHover={{ scale: 1.02 }} className="h-full">
                        <article id={projet.id}>
                          <Card onClick={() => { setSelectedProject(projet); setModalOpen(true); }} className="overflow-hidden transition-all h-full hover:shadow-2xl cursor-pointer">
                            <div className="relative group">
                              <PictureCard src={projet.image_principale} alt={projet.titre} buildSrc={buildSrc} />
                              <div className="absolute inset-0 bg-gradient-to-t from-black/25 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300" />
                              <div className="absolute top-4 left-4">
                                <span className="px-3 py-1 bg-white/90 backdrop-blur-sm rounded-full text-xs font-semibold text-[#2d7a4b] uppercase">{projet.categorie}</span>
                              </div>
                              {projet.statut && (
                                <div className="absolute top-4 right-4">
                                  <span className={`px-3 py-1 rounded-full text-xs font-semibold ${projet.statut === 'termine' ? 'bg-green-500 text-white' : 'bg-yellow-500 text-white'}`}>
                                    {projet.statut === 'termine' ? 'Terminé' : 'En cours'}
                                  </span>
                                </div>
                              )}
                            </div>
                      <div className="p-6">
                        <h3 className="text-xl font-bold text-gray-900 mb-2">{projet.titre}</h3>
                        {projet.description && (
                          <p className="text-gray-600 mb-4 line-clamp-3">{projet.description}</p>
                        )}
                        <div className="flex flex-wrap gap-4 items-center text-sm text-gray-500">
                          {projet.localisation && (
                            <div className="flex items-center gap-2"><MapPin className="w-4 h-4" />{projet.localisation}</div>
                          )}
                          {projet.superficie && (
                            <div className="flex items-center gap-2"><Building2 className="w-4 h-4" />{projet.superficie}</div>
                          )}
                          {projet.duree && (
                            <div className="flex items-center gap-2"><Calendar className="w-4 h-4" />Durée: {projet.duree}</div>
                          )}
                        </div>

                        <div className="flex gap-3 mt-4">
                          <Link to={`/projets/${projet.id}`} onClick={(e) => e.stopPropagation()}>
                            <button className="inline-flex items-center gap-2 px-4 py-3 bg-[#2d7a4b] text-white rounded-md hover:bg-[#255f3f] transition">
                              Voir plus
                            </button>
                          </Link>
                          <Link to={`${createPageUrl("OffrePACH")}?type=${projet.id}`} onClick={(e) => e.stopPropagation()}>
                            <button className="px-4 py-3 border border-gray-200 rounded-md hover:bg-gray-50 transition text-sm">
                              Demander un devis
                            </button>
                          </Link>
                        </div>
                      </div>
                    </Card>
                  </article>
                </motion.div>
              </motion.div>
            );
          })}
        </AnimatePresence>
      </div>
      <div className="mt-8 flex justify-center gap-3">
        {filteredProjets.length > visibleCount && (
          <Button className="bg-[#2d7a4b] text-white" onClick={() => setVisibleCount(Math.min(filteredProjets.length, visibleCount + INITIAL_VISIBLE))}>Charger plus</Button>
        )}
        {visibleCount > INITIAL_VISIBLE && (
          <Button variant="secondary" onClick={() => setVisibleCount(INITIAL_VISIBLE)}>Charger moins</Button>
        )}
        <Button variant="outline" onClick={() => setVisibleCount(filteredProjets.length)}>Voir tout</Button>
      </div>
    </>
  );

  return (
    <div>
      {/* Hero */}
      <section className="bg-gradient-to-br from-[#2d7a4b] to-[#4a9d6f] text-white py-20">
        <div className="max-w-7xl mx-auto px-4">
          <MotionContainer className="text-center max-w-3xl mx-auto">
            <motion.h1 variants={fadeUp} className="text-4xl md:text-5xl font-bold mb-6">
              Nos Réalisations
            </motion.h1>
            <motion.p variants={fadeUp} className="text-xl text-gray-100">
              Découvrez nos projets achevés et notre savoir-faire
            </motion.p>
          </MotionContainer>
        </div>
      </section>

      {/* Filtres */}
      <section className="py-8 bg-white border-b">
        <div className="max-w-7xl mx-auto px-4">
          <div className="flex flex-wrap gap-3 justify-between items-center">
              <div className="flex items-center gap-3 w-full md:w-auto">
              <Input value={q} onChange={(e) => setQ(e.target.value)} placeholder="Rechercher un projet, lieu, description..." className="w-72" />
              <div className="text-sm text-gray-600">{filteredProjets.length} projet(s)</div>
            </div>
            <div className="flex flex-wrap gap-3 justify-center">
              {(dynamicCategories || categories).map((cat) => (
                <Button
                  key={cat.value}
                  variant={filter === cat.value ? "default" : "outline"}
                  onClick={() => setFilter(cat.value)}
                  className={filter === cat.value ? "bg-[#2d7a4b] hover:bg-[#4a9d6f] text-white" : ""}
                >
                  {cat.label}
                </Button>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Galerie de Projets */}
      <section className="py-20 bg-gray-50">
        <div className="max-w-7xl mx-auto px-4">
          {galleryContent}
        </div>
      </section>
      {/* Project Modal */}
      <ProjectModal open={modalOpen} onClose={() => setModalOpen(false)} project={selectedProject} />
    </div>
  );
}