import React, { useMemo, useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import pachContent from 'entites/pach_content.json';
// Try to use auto-generated projects JSON when available (produced by scripts/ingest_projects.js)
let autoProjects = null;
try {
  // eslint-disable-next-line global-require
  const auto = require('entites/pach_projects_auto.json');
  if (auto && Array.isArray(auto.projects)) autoProjects = auto.projects;
} catch (e) {
  autoProjects = null;
}
// Also support the newer `projets_auto.json` manifest generated by scripts/ingest_projets.js
let autoProjectsAlt = null;
try {
  // eslint-disable-next-line global-require
  const alt = require('entites/projets_auto.json');
  if (alt && Array.isArray(alt.projects)) autoProjectsAlt = alt.projects;
} catch (e) {
  autoProjectsAlt = null;
}
import Lightbox from 'components/ui/lightbox2';
import { Button } from 'components/ui/button';
import { ArrowLeft, Download } from 'lucide-react';

function buildSrc(url, w) {
  if (!url) return url;
  // Unsplash style: replace or append width param
  try {
    const [base, q] = url.split('?');
    const params = new URLSearchParams(q || '');
    params.set('w', String(w));
    params.set('q', params.get('q') || '80');
    return `${base}?${params.toString()}`;
  } catch (e) {
    return url;
  }
}

export default function ProjectDetail() {
  const { id } = useParams();
  const project = useMemo(() => {
    // search in main pachContent first
    const fromContent = (pachContent.projets || []).find(p => String(p.id) === String(id));
    if (fromContent) return fromContent;
    // then search in auto-generated projects if present
    // check both possible auto-generated manifests
    const candidates = [];
    if (autoProjects) candidates.push(...autoProjects);
    if (autoProjectsAlt) candidates.push(...autoProjectsAlt);
    if (candidates.length) {
      const fromAuto = candidates.find(p => String(p.id) === String(id));
      if (fromAuto) return fromAuto;
    }
    return null;
  }, [id]);
  const [lightboxOpen, setLightboxOpen] = useState(false);
  const [lightboxIndex, setLightboxIndex] = useState(0);

  if (!project) {
    return (
      <div className="max-w-4xl mx-auto py-20 px-4">
        <h2 className="text-2xl font-bold">Projet introuvable</h2>
        <p className="mt-4">Le projet demandé n'existe pas ou a été déplacé.</p>
        <Link to="/programmepach#nos-projets-pach">
          <Button className="mt-6 inline-flex items-center"><ArrowLeft className="mr-2"/>Retour aux projets</Button>
        </Link>
      </div>
    );
  }

  // Normalize images: support both string entries and object entries {url,type,alt}
  const rawImages = (project.images || []).slice();
  // ensure the main image is first and has a type 'exterieur' as default if not present
  const mainObj = project.image_principale ? { url: project.image_principale, type: 'exterieur', alt: project.titre } : null;
  const normalized = [];
  if (mainObj) normalized.push(mainObj);
  rawImages.forEach((it) => {
    if (!it) return;
    if (typeof it === 'string') normalized.push({ url: it, type: 'exterieur', alt: project.titre });
    else normalized.push({ url: it.url || it.src || '', type: (it.type || 'interieur'), alt: (it.alt || project.titre) });
  });

  const images = normalized.filter(Boolean);

  const [filter, setFilter] = useState('all'); // 'all' | 'interieur' | 'exterieur'
  const filteredImages = images.filter(img => filter === 'all' ? true : (img.type === filter));

  return (
    <div className="min-h-screen py-12 bg-white">
      <div className="max-w-6xl mx-auto px-4">
            <div className="mb-6 flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-bold text-gray-900">{project.titre}</h1>
            <p className="text-sm text-gray-600 mt-1">{project.localisation} • {project.superficie || ''} • {project.duree || ''}</p>
          </div>
          <div className="flex gap-3">
            <Link to="/programmepach#nos-projets-pach">
              <Button variant="outline" className="inline-flex items-center"><ArrowLeft className="mr-2"/>Retour</Button>
            </Link>
            <a href={images[0]} target="_blank" rel="noreferrer" className="inline-flex">
              <Button className="inline-flex items-center bg-[#2d7a4b] text-white"><Download className="mr-2"/>Télécharger</Button>
            </a>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          <div className="lg:col-span-2">
            {/* Main gallery: large hero image + grid */}
            <div className="mb-4">
              {/* Hero image uses the first available filtered image or the first image overall */}
              <button onClick={() => { setLightboxIndex( images.indexOf(filteredImages[0] || images[0]) || 0); setLightboxOpen(true); }} className="block w-full">
                <picture>
                  <source srcSet={`${buildSrc((filteredImages[0] || images[0]).url,1600)} 1600w, ${buildSrc((filteredImages[0] || images[0]).url,1000)} 1000w`} />
                  <img src={buildSrc((filteredImages[0] || images[0]).url,1200)} alt={(filteredImages[0] || images[0]).alt || project.titre} className="w-full h-[520px] object-cover rounded-lg shadow-md" loading="lazy" />
                </picture>
              </button>
            </div>

            <div className="mb-4 flex items-center gap-3">
              <div className="flex-shrink-0">
                <span className="text-sm text-gray-600">Filtrer :</span>
              </div>
              <div className="flex gap-2">
                <button onClick={() => setFilter('all')} className={`px-3 py-1 rounded ${filter==='all' ? 'bg-[#2d7a4b] text-white' : 'bg-gray-100 text-gray-700'}`}>Toutes</button>
                <button onClick={() => setFilter('interieur')} className={`px-3 py-1 rounded ${filter==='interieur' ? 'bg-[#2d7a4b] text-white' : 'bg-gray-100 text-gray-700'}`}>Intérieur</button>
                <button onClick={() => setFilter('exterieur')} className={`px-3 py-1 rounded ${filter==='exterieur' ? 'bg-[#2d7a4b] text-white' : 'bg-gray-100 text-gray-700'}`}>Extérieur</button>
              </div>
            </div>

            <div className="columns-2 sm:columns-3 gap-3 space-y-3">
              {filteredImages.map((img, i) => (
                <button key={i} onClick={() => { setLightboxIndex(images.indexOf(img)); setLightboxOpen(true); }} className="break-inside-avoid overflow-hidden rounded-md block group">
                  <picture>
                    <source srcSet={`${buildSrc(img.url,1200)} 1200w, ${buildSrc(img.url,800)} 800w, ${buildSrc(img.url,400)} 400w`} />
                    <img src={buildSrc(img.url,800)} alt={img.alt || project.titre} className="w-full h-auto object-cover group-hover:scale-105 transform transition duration-300 rounded-md" loading="lazy" />
                  </picture>
                  <div className="mt-1 text-xs text-gray-600">{img.type === 'interieur' ? 'Intérieur' : 'Extérieur'}</div>
                </button>
              ))}
            </div>
          </div>

          <aside className="space-y-6">
            <div className="bg-white p-6 rounded-lg shadow">
              <h3 className="text-lg font-semibold mb-2">Détails</h3>
              <p className="text-gray-700 mb-3">{project.description}</p>
              <ul className="text-sm text-gray-600 space-y-2">
                {project.localisation && <li><strong>Localisation:</strong> {project.localisation}</li>}
                {project.superficie && <li><strong>Superficie:</strong> {project.superficie}</li>}
                {project.duree && <li><strong>Durée:</strong> {project.duree}</li>}
                {project.statut && <li><strong>Statut:</strong> {project.statut === 'termine' ? 'Terminé' : 'En cours'}</li>}
              </ul>
            </div>

            <div className="bg-white p-6 rounded-lg shadow">
              <h4 className="text-md font-semibold mb-3">Actions</h4>
              <div className="space-y-3">
                <a href={createContactUrl()} className="block">
                  <Button className="w-full">Contacter pour ce projet</Button>
                </a>
                <button onClick={() => { setLightboxIndex(0); setLightboxOpen(true); }} className="w-full inline-flex justify-center">
                  <Button variant="outline">Voir la galerie</Button>
                </button>
              </div>
            </div>
          </aside>
        </div>
      </div>

      <Lightbox images={images} initialIndex={lightboxIndex} open={lightboxOpen} onClose={() => setLightboxOpen(false)} />
    </div>
  );
}

function createContactUrl() {
  // fallback: use contact page
  return '/contact';
}
